// Generated by CoffeeScript 1.10.0
(function() {
  var modulo = function(a, b) { return (+a % (b = +b) + b) % b; };

  document.addEventListener('DOMContentLoaded', function() {
    var hidePreview, imgsSize, lastPreviewImg, leftArrow, previewDiv, previewImg, rightArrow, showPreview;
    previewDiv = document.querySelector('#preview');
    previewImg = document.querySelector('#preview > img');
    rightArrow = document.querySelector('.right-arrow');
    leftArrow = document.querySelector('.left-arrow');
    imgsSize = document.querySelectorAll('.img').length;
    lastPreviewImg = 0;
    showPreview = function(img) {
      previewDiv.style.display = 'flex';
      previewImg.src = img.src;
      return lastPreviewImg = Number(img.id.match(/\d+$/));
    };
    hidePreview = function() {
      return previewDiv.style.display = 'none';
    };
    Array.from(document.querySelectorAll('.img')).forEach(function(i) {
      return i.onclick = function(e) {
        return showPreview(e.target);
      };
    });
    previewDiv.onclick = hidePreview;
    previewImg.onclick = function(e) {
      return e.stopPropagation();
    };
    rightArrow.onclick = function(e) {
      var id;
      e.stopPropagation();
      id = modulo(lastPreviewImg + 1, imgsSize);
      return showPreview(document.querySelector("#id" + id));
    };
    return leftArrow.onclick = function(e) {
      var id;
      e.stopPropagation();
      id = modulo(lastPreviewImg - 1, imgsSize);
      return showPreview(document.querySelector("#id" + id));
    };
  });

}).call(this);
